# Generated by Django 3.2.2 on 2021-05-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_a_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco_a',
            name='cpf',
            field=models.IntegerField(),
        ),
    ]
