# Generated by Django 3.2.2 on 2021-05-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_a_app', '0002_alter_banco_a_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco_a',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='banco_a',
            name='endereco',
            field=models.CharField(max_length=50),
        ),
    ]
